LTO_ENABLE = yes

VIA_ENABLE = yes
VIAL_ENABLE = yes

COMBO_ENABLE = yes
TAP_DANCE_ENABLE = yes

EXTRAKEY_ENABLE  = yes
MOUSEKEY_ENABLE  = yes
KEY_OVERRIDE_ENABLE = yes
NKRO_ENABLE      = yes

RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812
VIALRGB_ENABLE = yes
WS2812_DRIVER = vendor

AUDIO_ENABLE = no

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
BOOTMAGIC_ENABLE = no

MAGIC_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
